# Generated by Django 5.1.2 on 2024-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Proveedor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
