# Generated by Django 5.1.2 on 2024-10-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultarInv', '0002_categoria_historial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='numero_lote',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
