# Generated by Django 5.1.2 on 2024-10-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultarInv', '0003_lote_numero_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
