# Generated by Django 5.1.2 on 2024-11-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultarInv', '0004_consultaproductos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultaProductos',
        ),
        migrations.AlterField(
            model_name='lote_historial',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
