# Generated by Django 5.1.2 on 2024-11-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultarInv', '0005_delete_consultaproductos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
